# Generated by Django 2.1.1 on 2018-10-19 21:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('P8', 'Pravega 2018'), ('P7', 'Pravega 2017'), ('P6', 'Pravega 2016'), ('I0', 'Hidden')], max_length=2)),
                ('description', models.CharField(max_length=280)),
                ('image_file', models.ImageField(upload_to='archiveimages/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='InOtherWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('challengeNo', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('snippet', models.ImageField(blank=True, upload_to='InOtherWords/snippets')),
                ('question_PDF', models.FileField(upload_to='InOtherWords/Question_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('answer_PDF', models.FileField(blank=True, upload_to='InOtherWords/answer_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('link_form', models.CharField(default='#', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InOtherWordsChallenge01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city01', models.CharField(blank=True, max_length=200, null=True)),
                ('city02', models.CharField(blank=True, max_length=200, null=True)),
                ('city03', models.CharField(blank=True, max_length=200, null=True)),
                ('city04', models.CharField(blank=True, max_length=200, null=True)),
                ('city05', models.CharField(blank=True, max_length=200, null=True)),
                ('city06', models.CharField(blank=True, max_length=200, null=True)),
                ('city07', models.CharField(blank=True, max_length=200, null=True)),
                ('city08', models.CharField(blank=True, max_length=200, null=True)),
                ('city09', models.CharField(blank=True, max_length=200, null=True)),
                ('city10', models.CharField(blank=True, max_length=200, null=True)),
                ('bonusquestion', models.TextField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InOtherWordsChallenge02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placesOrder', models.CharField(blank=True, max_length=20, null=True)),
                ('question2', models.TextField(blank=True, max_length=400, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InOtherWordsChallenge03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField(blank=True, max_length=400, null=True)),
                ('question2a', models.CharField(blank=True, max_length=30, null=True)),
                ('question2b', models.CharField(blank=True, max_length=30, null=True)),
                ('question2c', models.CharField(blank=True, max_length=30, null=True)),
                ('question2d', models.CharField(blank=True, max_length=30, null=True)),
                ('question2e', models.CharField(blank=True, max_length=30, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LetsTalkScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('youtube_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceQuizzine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=280)),
                ('image_file', models.ImageField(upload_to='sciencequizzine')),
            ],
        ),
    ]
