# Generated by Django 2.0.5 on 2018-05-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='mail_id',
            field=models.EmailField(max_length=60, null=True),
        ),
    ]
