# Generated by Django 2.1.1 on 2018-10-21 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('originals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOtherWordsChallenge04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField(blank=True, max_length=400, null=True)),
                ('question2', models.TextField(blank=True, max_length=400, null=True)),
                ('question3', models.TextField(blank=True, max_length=400, null=True)),
                ('question4', models.TextField(blank=True, max_length=400, null=True)),
                ('question5', models.TextField(blank=True, max_length=400, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
