# Generated by Django 2.0.5 on 2018-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0003_auto_20180509_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content_type',
            field=models.CharField(choices=[('A1', 'Blog'), ('A2', 'Articles'), ('A0', 'Hidden')], max_length=2),
        ),
        migrations.AlterField(
            model_name='images',
            name='content_type',
            field=models.CharField(choices=[('I1', 'Science Quizzine'), ('I2', 'Comic Strip'), ('I3', 'Gallery'), ('I4', 'Tuesday Trivia'), ('I5', 'Throwback Thursdays'), ('I6', 'Meme'), ('I0', 'Hidden')], max_length=2),
        ),
        migrations.AlterField(
            model_name='videos',
            name='content_type',
            field=models.CharField(choices=[('V1', 'Interview'), ('V0', 'Hidden')], max_length=2),
        ),
    ]
