# Generated by Django 2.0.5 on 2018-07-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0004_auto_20180510_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_file',
            field=models.ImageField(height_field='url_height', upload_to='images/%Y/%m/%d', width_field='url_width'),
        ),
    ]
