# Generated by Django 2.0.5 on 2018-07-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0005_auto_20180715_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_file',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
