# Generated by Django 2.0.5 on 2018-08-11 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0006_auto_20180715_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 23, 58, 12, 354330, tzinfo=utc), null=True)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('P18', 'Pravega 2018'), ('P17', 'Pravega 2017'), ('P16', 'Pravega 2016'), ('I0', 'Hidden')], max_length=2)),
                ('description', models.CharField(max_length=280)),
                ('image_file', models.ImageField(upload_to='archiveimages/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 23, 58, 12, 357322, tzinfo=utc), null=True)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('A1', 'Blog'), ('A2', 'Articles'), ('A0', 'Hidden')], max_length=2)),
                ('description', models.CharField(max_length=280)),
                ('author', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('cover_image', models.ImageField(null=True, upload_to='images/%Y/%m/%d')),
                ('number_of_views', models.PositiveIntegerField(default=0)),
                ('mail_id', models.EmailField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 23, 58, 12, 356325, tzinfo=utc), null=True)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('I1', 'Science Quizzine'), ('I2', 'Comic Strip'), ('I3', 'Gallery'), ('I4', 'Tuesday Trivia'), ('I5', 'Throwback Thursdays'), ('I6', 'Meme'), ('I0', 'Hidden')], max_length=2)),
                ('description', models.CharField(max_length=280)),
                ('image_file', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ScienceQuizine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 23, 58, 12, 355327, tzinfo=utc), null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=280)),
                ('image_file', models.ImageField(upload_to='sciencequizzine')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 23, 58, 12, 358319, tzinfo=utc), null=True)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('V1', 'Interview'), ('V0', 'Hidden')], max_length=2)),
                ('description', models.CharField(max_length=280)),
                ('text', models.TextField()),
                ('youtube_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
