# Generated by Django 2.0.5 on 2018-08-12 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0008_auto_20180812_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetsTalkScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 18, 38, 35, 904338, tzinfo=utc), null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('youtube_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 18, 38, 35, 906007, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 18, 38, 35, 905014, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sciencequizzine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 18, 38, 35, 903016, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 18, 38, 35, 907006, tzinfo=utc), null=True),
        ),
    ]
