# Generated by Django 2.0.5 on 2018-08-17 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0009_auto_20180813_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='archiveimage',
            name='content_type',
            field=models.CharField(choices=[('P8', 'Pravega 2018'), ('P7', 'Pravega 2017'), ('P6', 'Pravega 2016'), ('I0', 'Hidden')], max_length=2),
        ),
        migrations.AlterField(
            model_name='letstalkscience',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='sciencequizzine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
