# Generated by Django 2.1.1 on 2018-09-21 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0010_auto_20180818_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveimage',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
