# Generated by Django 2.1.1 on 2018-09-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0011_archiveimage_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveimage',
            name='create',
        ),
    ]
