# Generated by Django 2.1.1 on 2018-09-21 10:19

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('originals', '0012_remove_archiveimage_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOtherWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('snippet', models.ImageField(blank=True, upload_to='InOtherWords/snippets')),
                ('question_PDF', models.FileField(upload_to='InOtherWords/Question_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('answer_PDF', models.FileField(blank=True, upload_to='InOtherWords/answer_PDF', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('link_form', models.CharField(default='#', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
