# Generated by Django 2.1.1 on 2018-09-21 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('originals', '0013_inotherword'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOtherWordsChallenge01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city01', models.CharField(blank=True, max_length=200, null=True)),
                ('city02', models.CharField(blank=True, max_length=200, null=True)),
                ('city03', models.CharField(blank=True, max_length=200, null=True)),
                ('city04', models.CharField(blank=True, max_length=200, null=True)),
                ('city05', models.CharField(blank=True, max_length=200, null=True)),
                ('city06', models.CharField(blank=True, max_length=200, null=True)),
                ('city07', models.CharField(blank=True, max_length=200, null=True)),
                ('city08', models.CharField(blank=True, max_length=200, null=True)),
                ('city09', models.CharField(blank=True, max_length=200, null=True)),
                ('city10', models.CharField(blank=True, max_length=200, null=True)),
                ('bonusquestion', models.TextField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inotherword',
            name='challengeNo',
            field=models.IntegerField(default=0),
        ),
    ]
