#this file was directly transferred to the server for cryptothlon prelims

CRYPTOTHLON_PRELIMS_PDF = "vmPyJ2Gr2ZDpn1yQCKgZeouKt9WutochNzymCfIW4jwanoBq4IhKkr1y6NZ2OoBGAnOZCGgSpfI3JJczIqcXHpjB4CSUAyIYiZMKA8hVkhyXoOpjB4CSUAyIYiwH3f/Pravega2019_Cryptothlon_Prelims.pdf"
