# Generated by Django 2.1.3 on 2018-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('displayTitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField()),
                ('eventLink', models.CharField(default='#', max_length=200)),
                ('coordinatorName', models.CharField(blank=True, max_length=200)),
                ('coordinatorContact', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
