# Generated by Django 2.0.5 on 2018-09-09 20:32

from django.db import migrations, models
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasyaregistration',
            name='videoFile',
            field=models.FileField(null=True, upload_to=registration.models.LasyaRegistration.filePathGenerate, validators=[registration.field_helpers.lasya_file_validation]),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='videoFile',
            field=models.FileField(null=True, upload_to=registration.models.ProsceniumRegistration.filePathGenerate, validators=[registration.field_helpers.proscenium_file_validation]),
        ),
    ]
