# Generated by Django 2.0.5 on 2018-09-09 20:58

from django.db import migrations, models
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180910_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasyaregistration',
            name='email',
            field=models.EmailField(max_length=144),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='institution',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='place',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='teamLeader',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='teamName',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='videoFile',
            field=models.FileField(max_length=600, null=True, upload_to=registration.models.LasyaRegistration.filePathGenerate, validators=[registration.field_helpers.lasya_file_validation]),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='email',
            field=models.EmailField(max_length=144),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='institution',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada')], default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='place',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='teamLeader',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='teamName',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='videoFile',
            field=models.FileField(max_length=600, null=True, upload_to=registration.models.ProsceniumRegistration.filePathGenerate, validators=[registration.field_helpers.proscenium_file_validation]),
        ),
    ]
