# Generated by Django 2.0.5 on 2018-08-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180830_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminevents',
            name='registrationLink',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
