# Generated by Django 2.0.5 on 2018-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180830_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasyaregistration',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
