# Generated by Django 2.0.5 on 2018-09-09 21:04

from django.db import migrations, models
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180910_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasyaregistration',
            name='videoFileLink',
            field=models.EmailField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prosceniumregistration',
            name='videoFileLink',
            field=models.EmailField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='videoFile',
            field=models.FileField(blank=True, default='dummy', max_length=600, upload_to=registration.models.LasyaRegistration.filePathGenerate, validators=[registration.field_helpers.lasya_file_validation]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='videoFile',
            field=models.FileField(blank=True, default='dummy', max_length=600, upload_to=registration.models.ProsceniumRegistration.filePathGenerate, validators=[registration.field_helpers.proscenium_file_validation]),
            preserve_default=False,
        ),
    ]
