# Generated by Django 2.0.5 on 2018-09-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180910_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasyaregistration',
            name='videoFileLink',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='videoFileLink',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
