# Generated by Django 2.0.5 on 2018-09-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180910_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footprintsregistration',
            old_name='place',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='lasyaregistration',
            old_name='place',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='prosceniumregistration',
            old_name='place',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='place',
        ),
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(default='unknown_city', max_length=127),
        ),
    ]
