# Generated by Django 2.0.5 on 2018-08-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180830_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationActive', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=280)),
                ('registrationLink', models.CharField(default='#', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AdminEvent'),
        ),
        migrations.DeleteModel(
            name='AdminEvents',
        ),
    ]
