# Generated by Django 2.0.5 on 2018-09-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_userdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasyaregistration',
            name='isSubmit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='participantList',
            field=models.TextField(blank=True),
        ),
    ]
