# Generated by Django 2.0.5 on 2018-09-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180913_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasyaregistration',
            name='contact1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='contact2',
            field=models.CharField(max_length=20),
        ),
    ]
