# Generated by Django 2.0.5 on 2018-09-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20180913_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprintsregistration',
            name='isSubmit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prosceniumregistration',
            name='isSubmit',
            field=models.BooleanField(default=False),
        ),
    ]
