# Generated by Django 2.0.5 on 2018-09-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20180901_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminevent',
            name='description',
            field=models.TextField(),
        ),
    ]
