# Generated by Django 2.0.5 on 2018-09-01 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20180902_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminevent',
            name='registrationActive',
        ),
        migrations.AddField(
            model_name='adminevent',
            name='registrationStatus',
            field=models.CharField(choices=[('notyet', 'Not Yet'), ('opened', 'Open'), ('closed', 'Closed')], default='notyet', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
