# Generated by Django 2.0.5 on 2018-09-16 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0011_auto_20180916_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAmbassador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(default='unknown_name', max_length=127)),
                ('institution', models.CharField(max_length=144)),
                ('city', models.CharField(max_length=144)),
                ('email', models.EmailField(max_length=144)),
                ('contactForCalls', models.CharField(max_length=20)),
                ('contactForWhatsapp', models.CharField(max_length=20)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
