# Generated by Django 2.0.5 on 2018-09-02 11:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import registration.customfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0012_auto_20180902_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootprintsRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('teamName', models.CharField(max_length=200)),
                ('teamLeader', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact1', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10 digit phone number, prefixed by either 0, +91, or nothing', regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')])),
                ('contact2', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10 digit phone number, prefixed by either 0, +91, or nothing', regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')])),
                ('participantList', models.TextField()),
                ('videoFile', models.FileField(null=True, upload_to='fp238a576afovpy23mlzra/do9862x0k3pyl5bxnwxkr8/5n61kixjqfk8lbhkxxvw9m/lasya/%Y/%m/%d', validators=[registration.customfields.footprints_file_validation])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProsceniumRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('teamName', models.CharField(max_length=200)),
                ('teamLeader', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact1', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10 digit phone number, prefixed by either 0, +91, or nothing', regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')])),
                ('contact2', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10 digit phone number, prefixed by either 0, +91, or nothing', regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')])),
                ('participantList', models.TextField()),
                ('videoFile', models.FileField(null=True, upload_to='fp238a576afovpy23mlzra/do9862x0k3pyl5bxnwxkr8/5n61kixjqfk8lbhkxxvw9m/lasya/%Y/%m/%d', validators=[registration.customfields.proscenium_file_validation])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='lasyaregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='lasyaregistration',
            name='modify_date',
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='videoFile',
            field=models.FileField(null=True, upload_to='fp238a576afovpy23mlzra/do9862x0k3pyl5bxnwxkr8/5n61kixjqfk8lbhkxxvw9m/lasya/%Y/%m/%d', validators=[registration.customfields.lasya_file_validation]),
        ),
    ]
