# Generated by Django 2.0.5 on 2018-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_campusambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusambassador',
            name='last_modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
