# Generated by Django 2.0.5 on 2018-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_campusambassador_last_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusambassador',
            name='isSubmit',
            field=models.BooleanField(default=False),
        ),
    ]
