# Generated by Django 2.0.5 on 2018-09-04 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20180902_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='full_name',
            field=models.CharField(default='unknown_name', max_length=127),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdata_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
