# Generated by Django 2.0.5 on 2018-09-04 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20180904_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10 digit phone number, prefixed by either 0, +91, or nothing', regex='^\\+91\\d{10}$|^0\\d{10}$|^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='userdata',
            name='institution',
            field=models.CharField(default='unknown_institution', max_length=127),
        ),
        migrations.AddField(
            model_name='userdata',
            name='place',
            field=models.CharField(default='unknown_place', max_length=127),
        ),
    ]
