# Generated by Django 2.1.1 on 2018-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_campusambassador_issubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprintsregistration',
            name='contact1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='footprintsregistration',
            name='contact2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='contact1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prosceniumregistration',
            name='contact2',
            field=models.CharField(max_length=20),
        ),
    ]
