# Generated by Django 2.0.5 on 2018-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20180904_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='contact',
            field=models.CharField(default='NO_NUMBER', max_length=20),
        ),
    ]
