# Generated by Django 2.1.1 on 2018-10-06 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0015_auto_20180921_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleOfBandsRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('teamName', models.CharField(max_length=144)),
                ('teamLeader', models.CharField(max_length=144)),
                ('institution', models.CharField(max_length=144)),
                ('city', models.CharField(max_length=144)),
                ('email', models.EmailField(max_length=144)),
                ('contact1', models.CharField(max_length=20)),
                ('contact2', models.CharField(max_length=20)),
                ('participantList', models.TextField()),
                ('videoFileLink', models.URLField(blank=True, max_length=300)),
                ('videoFile', models.FileField(blank=True, max_length=600, upload_to=registration.models.BattleOfBandsRegistration.filePathGenerate, validators=[registration.field_helpers.battleofbands_file_validation])),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
