# Generated by Django 2.0.5 on 2018-09-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20180904_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='modify_date',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdata_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
