# Generated by Django 2.0.5 on 2018-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20180904_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprintsregistration',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lasyaregistration',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prosceniumregistration',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
