# Generated by Django 2.1.1 on 2018-10-13 23:45

from django.db import migrations, models
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20181014_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleofbandsregistration',
            name='audioVideoFile',
            field=models.FileField(blank=True, max_length=600, upload_to=registration.models.BattleOfBandsRegistration.filePathGenerate, validators=[registration.field_helpers.battleofbands_file_validation]),
        ),
    ]
