# Generated by Django 2.1.1 on 2018-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_adminevent_displaytitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminevent',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
