# Generated by Django 2.1.1 on 2018-10-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_wikimediaphotographyregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikimediaphotographyregistration',
            old_name='wkimediaUserID',
            new_name='wikimediaUserID',
        ),
    ]
