# Generated by Django 2.1.1 on 2018-10-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20181028_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasyaregistration',
            name='category',
            field=models.CharField(choices=[('solo', 'SOLO'), ('duet', 'DUET'), ('group', 'GROUP')], default='GROUP', max_length=10),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='teamLeader',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AlterField(
            model_name='lasyaregistration',
            name='teamName',
            field=models.CharField(blank=True, max_length=144),
        ),
    ]
