# Generated by Django 2.1.1 on 2018-10-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20181030_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleofbandsregistration',
            name='howyouknow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='campusambassador',
            name='howyouknow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='decoherenceregistration',
            name='howyouknow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='footprintsregistration',
            name='howyouknow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lasyaregistration',
            name='howyouknow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prosceniumregistration',
            name='howyouknow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wikimediaphotographyregistration',
            name='howyouknow',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
