# Generated by Django 2.1.1 on 2018-11-09 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0029_auto_20181104_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='PISRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('teamName', models.CharField(max_length=200)),
                ('member1name', models.CharField(max_length=200)),
                ('member1mobile', models.CharField(max_length=20)),
                ('member1email', models.EmailField(max_length=200)),
                ('member2name', models.CharField(blank=True, max_length=200)),
                ('member2mobile', models.CharField(blank=True, max_length=20)),
                ('member2email', models.EmailField(blank=True, max_length=200)),
                ('member3name', models.CharField(blank=True, max_length=200)),
                ('member3mobile', models.CharField(blank=True, max_length=20)),
                ('member3email', models.EmailField(blank=True, max_length=200)),
                ('ideaAbstract', models.TextField()),
                ('motivation', models.TextField()),
                ('prospects', models.TextField()),
                ('marketResearch', models.TextField()),
                ('prototyping', models.TextField()),
                ('institution', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('howyouknow', models.CharField(blank=True, max_length=200)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
