# Generated by Django 2.1.1 on 2018-11-17 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0031_auto_20181110_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecoherenceObjectiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qNo', models.IntegerField(blank=True, default=-1, unique=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('fakeText', models.TextField(blank=True, default='Please wait')),
                ('text', models.TextField(blank=True)),
                ('choice1', models.CharField(blank=True, max_length=600)),
                ('choice2', models.CharField(blank=True, max_length=600)),
                ('choice3', models.CharField(blank=True, max_length=600)),
                ('choice4', models.CharField(blank=True, max_length=600)),
                ('image', models.ImageField(blank=True, upload_to=registration.models.DecoherenceObjectiveQuestion.filePathGenerate)),
            ],
        ),
        migrations.CreateModel(
            name='DecoherencePrelim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('question01', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question02', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question03', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question04', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question05', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question06', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question07', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question08', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question09', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question10', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question11', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question12', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question13', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question14', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question15', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question16', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question17', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question18', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question19', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question20', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question21', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question22', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question23', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question24', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('question25', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=600)),
                ('subjectiveAnswers', models.FileField(blank=True, max_length=600, upload_to=registration.models.DecoherencePrelim.filePathGenerate, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('teamName', models.CharField(max_length=144)),
                ('institution', models.CharField(max_length=144)),
                ('city', models.CharField(max_length=144)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('modifyTimes', models.TextField(blank=True, default=' ')),
                ('email', models.EmailField(max_length=200)),
                ('decoherenceRegistration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.DecoherenceRegistration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DecoherenceSubjectiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qNo', models.IntegerField(blank=True, default=-1, unique=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('fakeText', models.TextField(blank=True, default='Please wait')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=registration.models.DecoherenceSubjectiveQuestion.filePathGenerate)),
            ],
        ),
        migrations.CreateModel(
            name='StatusDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('dtValue', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
