# Generated by Django 2.1.1 on 2018-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_decoherenceobjectivequestion_decoherenceprelim_decoherencesubjectivequestion_statusdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question05',
            field=models.CharField(blank=True, choices=[('A', 'aaaaa'), ('B', 'bbbb'), ('C', 'cccccccccc'), ('D', 'ddddddddddddddd dddddddddddd dddddddddddd')], max_length=600),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question06',
            field=models.CharField(blank=True, choices=[('A', 'dv'), ('B', 'fwsdf'), ('C', 'wrw'), ('D', 'qrq')], max_length=600),
        ),
    ]
