# Generated by Django 2.1.1 on 2018-11-17 17:28

import django.core.validators
from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_auto_20181117_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='subjectiveAnswers',
            field=models.FileField(blank=True, max_length=600, upload_to=registration.models.DecoherencePrelim.filePathGenerate, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip'])]),
        ),
    ]
