# Generated by Django 2.1.1 on 2018-11-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_auto_20181118_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question01',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question02',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question03',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question04',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question05',
            field=models.CharField(choices=[('A', 'aaaaa'), ('B', 'bbbb'), ('C', 'cccccccccc'), ('D', 'ddddddddddddddd dddddddddddd dddddddddddd'), ('S', 'ddddddddddddddd dddddddddddd dddddddddddd')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question06',
            field=models.CharField(choices=[('A', 'dv'), ('B', 'fwsdf'), ('C', 'wrw'), ('D', 'qrq'), ('S', 'qrq')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question07',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question08',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question09',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question10',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question11',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question12',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question13',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question14',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question15',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question16',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question17',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question18',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question19',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question20',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question21',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question22',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question23',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question24',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question25',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', 'D')], default='S', max_length=600, null=True),
        ),
    ]
