# Generated by Django 2.1.3 on 2018-11-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_impromptooregistration'),
        ('registration', '0042_auto_20181118_0325'),
    ]

    operations = [
    ]
