# Generated by Django 2.0.5 on 2018-11-20 17:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_auto_20181119_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etcregistration',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Physics', 'Physics'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Psychology', 'Psychology'), ('Economics', 'Economics')], max_length=58),
        ),
    ]
