# Generated by Django 2.0.5 on 2018-11-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_auto_20181120_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etcregistration',
            name='subjects',
        ),
        migrations.AddField(
            model_name='etcregistration',
            name='biology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etcregistration',
            name='chemistry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etcregistration',
            name='economics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etcregistration',
            name='mathematics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etcregistration',
            name='physics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etcregistration',
            name='psychology',
            field=models.BooleanField(default=False),
        ),
    ]
