# Generated by Django 2.1.1 on 2018-11-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0046_vignettoraregistration_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='etcregistration',
            name='other_subjects',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etcregistration',
            name='topic',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
