# Generated by Django 2.1.1 on 2018-11-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_auto_20181121_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etcregistration',
            name='other_subjects',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
