# Generated by Django 2.0.5 on 2018-11-20 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0047_debubularyregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptothlonRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('teamName', models.CharField(max_length=144)),
                ('participant1', models.CharField(max_length=200)),
                ('email1', models.EmailField(max_length=144)),
                ('contact1', models.CharField(max_length=20)),
                ('participant2', models.CharField(blank=True, max_length=200)),
                ('email2', models.EmailField(blank=True, max_length=144)),
                ('contact2', models.CharField(blank=True, max_length=20)),
                ('institution', models.CharField(max_length=144)),
                ('city', models.CharField(max_length=144)),
                ('howyouknow', models.CharField(blank=True, max_length=200)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
