# Generated by Django 2.1.1 on 2018-11-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_auto_20181121_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impromptooregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pppregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='etcregistration',
            name='howyouknow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vignettoraregistration',
            name='howyouknow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='ImpromptooRegistration',
        ),
        migrations.DeleteModel(
            name='PPPRegistration',
        ),
    ]
