# Generated by Django 2.1.1 on 2018-11-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_auto_20181121_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etcregistration',
            old_name='name',
            new_name='full_name',
        ),
    ]
