# Generated by Django 2.1.3 on 2018-11-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_auto_20181123_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemisticonrregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChemisticonrRegistration',
        ),
    ]
