# Generated by Django 2.1.3 on 2018-11-27 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0057_sciencejournalismregistration_articlefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISCRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=127)),
                ('institution', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('howyouknow', models.CharField(blank=True, max_length=200)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='sciencejournalismregistration',
            name='articleFile',
            field=models.FileField(blank=True, max_length=600, upload_to=registration.models.ScienceJournalismRegistration.filePathGenerate, validators=[registration.field_helpers.sciencejournalism_file_validation]),
        ),
    ]
