# Generated by Django 2.1.1 on 2018-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0058_auto_20181127_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question05',
            field=models.CharField(choices=[('A', 'aaaaa'), ('B', 'bbbb'), ('C', 'cccccccccc'), ('D', 'ddddddddddddddd dddddddddddd dddddddddddd'), ('S', '(Skip)')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question06',
            field=models.CharField(choices=[('A', 'dv'), ('B', 'fwsdf'), ('C', 'wrw'), ('D', 'qrq'), ('S', '(Skip)')], default='S', max_length=600, null=True),
        ),
    ]
