# Generated by Django 2.1.3 on 2018-12-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0059_auto_20181128_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question05',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', '(Skip)')], default='S', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='decoherenceprelim',
            name='question06',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('S', '(Skip)')], default='S', max_length=600, null=True),
        ),
    ]
