# Generated by Django 2.1.3 on 2018-12-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0064_auto_20181201_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibmhackathonregistration',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='ibmhackathonregistration',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='ibmhackathonregistration',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='ibmhackathonregistration',
            name='question4',
        ),
    ]
