# Generated by Django 2.1.3 on 2018-12-01 08:15

from django.db import migrations, models
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0066_auto_20181201_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='responseFile',
            field=models.FileField(blank=True, max_length=600, upload_to=registration.models.IBMHackathonRegistration.filePathGenerate, validators=[registration.field_helpers.ibmhackathon_file_validation]),
        ),
        migrations.AlterField(
            model_name='ibmhackathonregistration',
            name='question1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ibmhackathonregistration',
            name='question2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ibmhackathonregistration',
            name='question3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ibmhackathonregistration',
            name='question4',
            field=models.TextField(blank=True),
        ),
    ]
