# Generated by Django 2.1.3 on 2018-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0067_auto_20181201_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibmhackathonregistration',
            name='question1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ibmhackathonregistration',
            name='question2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ibmhackathonregistration',
            name='question3',
            field=models.TextField(blank=True),
        ),
    ]
