# Generated by Django 2.1.3 on 2018-12-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0069_remove_ibmhackathonregistration_responsefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibmhackathonregistration',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='ibmhackathonregistration',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='ibmhackathonregistration',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='ibmhackathonregistration',
            name='question4',
        ),
    ]
