# Generated by Django 2.1.3 on 2018-12-01 15:40

from django.db import migrations, models
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0072_auto_20181201_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibmhackathonregistration',
            name='responseFile',
            field=models.FileField(blank=True, max_length=600, upload_to=registration.models.IBMHackathonRegistration.filePathGenerate, validators=[registration.field_helpers.ibmhackathon_file_validation]),
        ),
    ]
