# Generated by Django 2.1.4 on 2018-12-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0073_auto_20181201_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibmhackathonregistration',
            name='full_name',
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='contact1',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='contact2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='contact3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='contact4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='email1',
            field=models.EmailField(default=0, max_length=144),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='email2',
            field=models.EmailField(blank=True, max_length=144),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='email3',
            field=models.EmailField(blank=True, max_length=144),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='email4',
            field=models.EmailField(blank=True, max_length=144),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='member1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='member2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='member3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='member4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='qualification1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='qualification2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='qualification3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='qualification4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ibmhackathonregistration',
            name='teamName',
            field=models.CharField(default=0, max_length=144),
            preserve_default=False,
        ),
    ]
