# Generated by Django 2.1.4 on 2018-12-17 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0074_auto_20181217_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptothlonPrelim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('a01', models.CharField(blank=True, max_length=24, null=True)),
                ('a07', models.CharField(blank=True, max_length=24, null=True)),
                ('a08', models.CharField(blank=True, max_length=24, null=True)),
                ('a09', models.CharField(blank=True, max_length=24, null=True)),
                ('a10', models.CharField(blank=True, max_length=24, null=True)),
                ('a11', models.CharField(blank=True, max_length=24, null=True)),
                ('a13', models.CharField(blank=True, max_length=24, null=True)),
                ('a16', models.CharField(blank=True, max_length=24, null=True)),
                ('a17', models.CharField(blank=True, max_length=24, null=True)),
                ('d02', models.CharField(blank=True, max_length=24, null=True)),
                ('d03', models.CharField(blank=True, max_length=24, null=True)),
                ('d04', models.CharField(blank=True, max_length=24, null=True)),
                ('d05', models.CharField(blank=True, max_length=24, null=True)),
                ('d06', models.CharField(blank=True, max_length=24, null=True)),
                ('d12', models.CharField(blank=True, max_length=24, null=True)),
                ('d13', models.CharField(blank=True, max_length=24, null=True)),
                ('d14', models.CharField(blank=True, max_length=24, null=True)),
                ('teamName', models.CharField(max_length=144)),
                ('institution', models.CharField(max_length=144)),
                ('city', models.CharField(max_length=144)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('modifyTimes', models.TextField(blank=True, default=' ', max_length=1200)),
                ('email', models.EmailField(max_length=200)),
                ('CryptothlonRegistration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.CryptothlonRegistration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
