# Generated by Django 2.1.4 on 2018-12-17 14:14

import django.core.validators
from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0074_auto_20181217_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='pisregistration',
            name='responseFile',
            field=models.FileField(blank=True, max_length=600, upload_to=registration.models.PISRegistration.filePathGenerate, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
