# Generated by Django 2.1.4 on 2018-12-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0075_cryptothlonprelim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptothlonprelim',
            old_name='CryptothlonRegistration',
            new_name='cryptothlonRegistration',
        ),
    ]
