# Generated by Django 2.1.3 on 2018-12-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0077_cryptothlonprelimdump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etcregistration',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
