# Generated by Django 2.1.3 on 2018-12-24 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0079_etcregisteredregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VignettoraRegisteredRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('articleFileLink', models.URLField(blank=True, max_length=300)),
                ('articleFile', models.FileField(blank=True, max_length=600, upload_to=registration.models.VignettoraRegisteredRegistration.filePathGenerate, validators=[registration.field_helpers.sciencejournalism_file_validation])),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
