# Generated by Django 2.1.3 on 2018-12-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0083_auto_20181229_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pisregistration',
            name='member1email',
            field=models.EmailField(default='sdwas@gmai.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pisregistration',
            name='member2email',
            field=models.EmailField(blank=True, default='sdwas@gmai.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pisregistration',
            name='member3email',
            field=models.EmailField(blank=True, default='sdwas@gmai.com', max_length=200),
            preserve_default=False,
        ),
    ]
