# Generated by Django 2.1.3 on 2018-12-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0084_auto_20181229_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='pisround2registration',
            name='selectionStatus',
            field=models.CharField(choices=[('notselected', 'Not Selected'), ('selected', 'Selected')], default='notselected', max_length=200),
        ),
    ]
