# Generated by Django 2.1.3 on 2019-01-03 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0086_auto_20181229_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUBGRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=127)),
                ('city', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('characterid', models.CharField(max_length=127)),
                ('whatsapp', models.CharField(max_length=20)),
                ('full_name1', models.CharField(max_length=127)),
                ('city1', models.CharField(max_length=200)),
                ('contact1', models.CharField(max_length=20)),
                ('characterid1', models.CharField(max_length=127)),
                ('whatsapp1', models.CharField(max_length=20)),
                ('howyouknow', models.CharField(blank=True, max_length=200)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('isSubmit', models.BooleanField(default=False)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
