# Generated by Django 2.1.4 on 2019-01-03 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.field_helpers
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0087_pubgregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceJournalismSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('articleFile', models.FileField(blank=True, max_length=600, upload_to=registration.models.ScienceJournalismSubmission.filePathGenerate, validators=[registration.field_helpers.sciencejournalism_file_validation])),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('scienceJournalismRegistration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.ScienceJournalismRegistration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
