# Generated by Django 2.1.4 on 2019-01-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0088_sciencejournalismsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubgregistration',
            name='team_name',
            field=models.CharField(default='default', max_length=127),
            preserve_default=False,
        ),
    ]
