# Generated by Django 2.1.4 on 2019-01-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0089_pubgregistration_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencejournalismsubmission',
            name='isSubmit',
            field=models.BooleanField(default=True),
        ),
    ]
