# Generated by Django 2.1.4 on 2019-01-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0090_sciencejournalismsubmission_issubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pisround2registration',
            name='implementaton',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pisround2registration',
            name='originality',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pisround2registration',
            name='societalImpact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pisround2registration',
            name='viability',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
