# Generated by Django 2.1.4 on 2019-01-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0092_molecularmuralsregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecularmuralsregistration',
            name='contact3',
        ),
        migrations.RemoveField(
            model_name='molecularmuralsregistration',
            name='email3',
        ),
        migrations.RemoveField(
            model_name='molecularmuralsregistration',
            name='participant3',
        ),
        migrations.RemoveField(
            model_name='molecularmuralsregistration',
            name='qualification3',
        ),
    ]
