# Generated by Django 2.1.4 on 2019-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0096_inotherwordssubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inotherwordssubmission',
            name='isSubmit',
        ),
        migrations.AddField(
            model_name='inotherwordssubmission',
            name='city',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AddField(
            model_name='inotherwordssubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inotherwordssubmission',
            name='institution',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AlterField(
            model_name='inotherwordssubmission',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
        ),
    ]
