# Generated by Django 2.1.4 on 2019-01-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0097_auto_20190118_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inotherwordssubmission',
            name='answer',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='inotherwordssubmission',
            name='comments',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
