# Generated by Django 2.1.4 on 2019-01-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0099_auto_20190118_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inotherwordssubmission',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1),
        ),
    ]
