# Generated by Django 2.0.5 on 2018-08-12 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 0, 21, 36, 231317, tzinfo=utc), null=True),
        ),
    ]
