# Generated by Django 2.0.5 on 2018-08-12 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_auto_20180812_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 18, 38, 35, 900767, tzinfo=utc), null=True),
        ),
    ]
