# Generated by Django 2.0.5 on 2018-08-17 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0003_auto_20180813_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
