# Generated by Django 2.0.5 on 2018-08-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0004_auto_20180818_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='title',
        ),
    ]
