# Generated by Django 2.0.5 on 2018-08-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0005_remove_update_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='title',
            field=models.CharField(default='Title', max_length=200),
            preserve_default=False,
        ),
    ]
