# Generated by Django 2.1.1 on 2018-10-19 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
